### ISSUE TITLE
sqlite3.OperationalError

### ISSUE THREAD

**Issue by psykos** [psykos/psychotest#1]
* On the first run, program drops an error.
* On the second run, program runs normally.

Traceback (most recent call last):
  File "/home/o_o/psychotest/psychotest.py", line 184, in <module>
    main()
  File "/home/o_o/psychotest/psychotest.py", line 172, in main
    departments = display_depts()
  File "/home/o_o/psychotest/psychotest.py", line 67, in display_depts
    con = create_db()
  File "/home/o_o/psychotest/psychotest.py", line 14, in create_db
    con.executescript(schema)
sqlite3.OperationalError: near ")": syntax error

**Comment by psykos** [comment]
The error is because of wrong schema.sql indents formatting. Resolving it now.

**Comment by psykos** [comment]
Schema corrected. Issue solved.
